name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Change this if your default branch differs

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Security best-practice
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare deployment content
        run: |
          mkdir deploy
          cp -r editor/* deploy/
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment