name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # or whichever branch you want

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Copy Editor to Public Folder
        run: |
          rm -rf public || true
          cp -r editor public
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
